### ISSUE TITLE
Test "kedr_trace.blocking_read.01" hangs or crashes the system (kernel 4.5.0)

### ISSUE THREAD

**Issue by euspectre** [euspectre/kedr#31]
On a RHEL7-based system with the mainline kernel 4.5.0 (built on that system), "kedr_trace.blocking_read.01" test seems to hang the system completely: no reaction to keyboard, pings and such.

I re-checked that by running that test separately - same problem.

It might be a crash, although I could not capture the log yet, unfortunately. The system seems to hang before that info is written. Kdump fails to run too.

It is worth trying to reproduce the problem on CentOS 7 but I haven't done this yet.

I have recently fixed the build of KEDR on kernel 4.5 but those changes are pretty straightforward, so it seems unlikely they cause this problem.

Andrey, could you take a look?

**Comment by Tsyvarev** [comment]
I have observed similar problems on Fedora 23 (kernel 4.3). Sometimes system doesn't crash completely, and there is some valuable log in that case. I will investigate the problem.

**Comment by euspectre** [comment]
Fixed by the commit 677e46176f0d, "Fix kedr_trace crashing system during kedr_trace.blocking_read.01"
