### ISSUE TITLE
Cent 7.2 - kernel 3.10.0-327.el7.x86_64

### ISSUE THREAD

**Issue by imay81** [euspectre/kedr#35]
Hello!

I haven't been able to get kedr to work on a Cent 3.10 kernel.  Is this kernel version not supported?  I used kedr all the time on Cent 6, which was still running 2.6.32.  No matter what version of kedr I try, I get the following crash when I try and load my module or run the kedr test suite.

[124824.247744] BUG: unable to handle kernel paging request at ffffffffa0b1f788
[124824.248114] IP: [<ffffffffa058d7c5>] do_process_area+0x235/0x290 [kedr]

I'm in desperate need of a memory leak detection tool, so I'd love if I'm just doing something stupid!

Thanks,
Ian

**Comment by euspectre** [comment]
Please, see if the simple patch from https://github.com/euspectre/kedr/pull/33 helps. For CentOS, it might work.

Some changes related to making code read-only have been backported to the RHEL's/CentOS'es kernel from the kernel 3.16+. KEDR is not aware of that at the moment, this causes problems.

**Comment by imay81** [comment]
That did it!  Thank you so much for the quick response.  KEDR has been an incredibly helpful and useful tool for me.  I appreciate all the work you've put into it.

Thanks,
Ian

**Comment by euspectre** [comment]
Glad to hear that!
As for the problem, the complete fix is probably going to be different to handle non-CentOS cases as well. For CentOS 7 that simple one should be fine for now.
