### ISSUE TITLE
trace_config.h not found

### ISSUE THREAD

**Issue by eknoes** [euspectre/kedr#45]
Hi,

Following your installation instructions for building from source, I get the following error on make:

```
[ 75%] Building kernel module kedr_trace
/tmp/kedr/trace/sources/trace/trace_buffer.c:5:10: fatal error: trace_config.h: No such file or directory
```

The file `trace_config.h` exists in `/tmp/kedr/trace/` but not in `/tmp/kedr/trace/sources/trace/`.

**Comment by euspectre** [comment]
Interesting. Which version of KEDR are you building?

Please also post the output of cmake when you run it.

**Comment by eknoes** [comment]
I build using the current master branch. The log for cmake & make is here: https://gist.github.com/eknoes/d3667899f5f400ceecd468243f648414

I run the current kernel 4.15.3

**Comment by euspectre** [comment]
Thanks, I'll take a look.

For now, you can try to build KEDR without tracing support: it should not be needed for LeakCheck and fault simulation facilities anyway. Just add -DKEDR_TRACE=OFF when running cmake and see if it builds OK now.

**Comment by eknoes** [comment]
That works, thanks!

**Comment by euspectre** [comment]
I have disabled building of kedr_trace.ko by default. It was needed for call monitoring only which has been de-facto deprecated and unmaintained for a long time. Neither LeakCheck nor fault simulation use these tracing facilities, so they should be fine without it.
