### ISSUE TITLE
Error while Installing with Call Tracing

### ISSUE THREAD

**Issue by nitinkp470** [euspectre/kedr#48]
/home/***/Downloads/kedr/kedr-build/payloads_callm/common_mm/payload.c: In function ‘kedr_post___alloc_pages_nodemask’:
/home/***/Downloads/kedr/kedr-build/payloads_callm/common_mm/payload.c:845:22: error: ‘zonelist’ undeclared (first use in this function)
   __entry.zonelist = zonelist;
                      ^
/home/***/Downloads/kedr/kedr-build/payloads_callm/common_mm/payload.c:845:22: note: each undeclared identifier is reported only once for each function it appears in
scripts/Makefile.build:330: recipe for target '/home/***/Downloads/kedr/kedr-build/payloads_callm/common_mm/payload.o' failed
make[4]: *** [/home/***/Downloads/kedr/kedr-build/payloads_callm/common_mm/payload.o] Error 1
Makefile:1571: recipe for target '_module_/home/***/Downloads/kedr/kedr-build/payloads_callm/common_mm' failed
make[3]: *** [_module_/home/***/Downloads/kedr/kedr-build/payloads_callm/common_mm] Error 2
payloads_callm/common_mm/CMakeFiles/kedr_cm_cmm.dir/build.make:65: recipe for target 'payloads_callm/common_mm/kedr_cm_cmm.ko' failed
make[2]: *** [payloads_callm/common_mm/kedr_cm_cmm.ko] Error 2
CMakeFiles/Makefile2:1153: recipe for target 'payloads_callm/common_mm/CMakeFiles/kedr_cm_cmm.dir/all' failed
make[1]: *** [payloads_callm/common_mm/CMakeFiles/kedr_cm_cmm.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by euspectre** [comment]
Call tracing has been deprecated and unsupported for a long time. It will likely be removed from KEDR in some future version.

It served its purpose in the past but now Ftrace and perf (provided by the kernel itself) are far superior.
