### ISSUE TITLE
kedr_capture_trace not found

### ISSUE THREAD

**Issue by 976772537** [euspectre/kedr#52]
I used these commands to configure KEDR Framework in ubuntu12.04 (Linux 3.5.0).
$ cmake -DKEDR_STANDARD_CALLM_PAYLOADS=on ../kedr-0.6/sources/
$ make && make install
But in my /usr/local/bin only have `kedr` and `kedr_gen`. Can you tell me how to find `kedr_capture_trace` ?

**Comment by euspectre** [comment]
kedr_capture_trace is deprecated and should not be built by default.

I'd suggest using Ftrace facilities available in the kernel itself (https://www.kernel.org/doc/html/latest/trace/ftrace.html), they are much more advanced now.

**Comment by euspectre** [comment]
As for KEDR tools as they are now (leak checking and fault simulation), I have almost no time to develop them further.

For now, they are probably suitable for educational purposes only.
